In [3]:
print('Hello world')

Hello world

In [4]:
import pandas as pd

df = pd.read_excel('Base_vendas.xlsx')

display(df.head())

for i in df.columns:
    print(i)

,Produto,Qtd Vendida,Data,Loja,Preço Unitário,Nome,Sobrenome,Gênero,Unnamed: 8
0,iPhone,4,2020-01-01,Salvador - BA,5300,Wilson,Arruda,M,NaN
1,SmartWatch,5,2020-01-01,São Paulo - SP,1400,Anna,Silva,F,NaN
2,Câmera,2,2020-01-01,Curitiba - PR,2100,Natalia,Oliveira,F,NaN
3,Notebook,2,2020-01-01,São Paulo - SP,3500,Caio,Vianna,M,NaN
4,Android,1,2020-01-01,Salvador - BA,3400,Maria,Ribeiro,F,NaN

Produto
Qtd Vendida
Data
Loja
Preço Unitário
Nome
Sobrenome
Gênero
Unnamed: 8

## Aula 06 - Atividade Prática

### Pandas - Dataset - base_vendas 

### Você foi contratado como analista de dados e sua primeira atividade:

* Qual o faturamento da empresa? (vamos fazer juntos!)
* Quais produtos são vendidos?
* Qual o produto mais vendido? 
* Como foi o faturamente das vendas por gênero?
* Relacione as vendas por loja.

In [ ]:
# Criar a coluna faturamento
# Qtd Vendida * Preço Unitário

df['Faturamento'] = df['Qtd Vendida'] * df['Preço Unitário']
display(df[['Produto', 'Qtd Vendida', 'Preço Unitário', 'Faturamento' ]].head())

#OBS: A coluna faturamento existe apenas no data frame...
# No arquivo Base_vendas.xlsx a coluna não existe.

      Produto  Qtd Vendida  Preço Unitário  Faturamento
0      iPhone            4            5300        21200
1  SmartWatch            5            1400         7000
2      Câmera            2            2100         4200
3    Notebook            2            3500         7000
4     Android            1            3400         3400

In [42]:
# Identificar a coluna de produtos

produtos = df['Produto'].unique()

for i in produtos:
    print(i)

iPhone
SmartWatch
Câmera
Notebook
Android
Televisão
Tablet

In [46]:
# Identificar o produto mais vendido

pmv = df.groupby(['Produto'])['Qtd Vendida'].sum().sort_values(ascending=False).head(1)
print(pmv)

Produto
iPhone    7190
Name: Qtd Vendida, dtype: int64

In [48]:
# Faturamento das vendas por gênero

fgenero = df.groupby('Gênero')['Faturamento'].sum()
print(fgenero)

Gênero
F    44776400
M    54543100
Name: Faturamento, dtype: int64

In [49]:
# Relacione

fatLoja = df.groupby('Loja')['Faturamento'].sum()
print(fatLoja)

Loja
Belo Horizonte - MG    14436100
Campinas - SP           7011000
Curitiba - PR           4877300
Goiânia - GO            9511900
Guarulhos - SP          8101300
Niterói - RJ            7095700
Nova Iguaçu - RJ        7188800
Porto Alegre - RS       6785200
Recife - PE             2407000
Rio de Janeiro - RJ     7573900
Salvador - BA           7419900
São Paulo - SP         16911400
Name: Faturamento, dtype: int64